blank_issues_enabled: false
contact_links:
  - name: Ask a Question / Start a Discussion
    url: https://github.com/r13xr13/conflict-globe.gl/discussions
    about: For general questions or ideas that don't fit a bug report or feature request, use Discussions.
